# Generated by Django 4.0.2 on 2022-02-28 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_produtos_linkproduto_produtos_mlproduto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='mlproduto',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
