# Generated by Django 4.0.2 on 2022-02-28 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0003_alter_produtos_mlproduto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produtos',
            name='linkproduto',
        ),
    ]
