# Generated by Django 4.0.2 on 2022-02-28 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0004_remove_produtos_linkproduto'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtos',
            name='linkproduto',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
